[package]
name = "xmodem"
version = "0.1.3"
authors = ["Allen Welkie <allen.welkie@gmail.com>"]
keywords = ["xmodem", "ymodem", "zmodem", "serial"]
repository = "https://github.com/awelkie/xmodem.rs"
license = "MIT"
description = "An implementation of the XMODEM file-transfer protocol."

[dependencies]
log = "^0.3"
crc16 = "^0.3"

[dev-dependencies]
tempfile = "^2.0"
rand = "^0.3"
